### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by javiermortiz** [MelodyLayne/WallStHoldEm#1]
Hi Melody, here are some comments about your docs:

MVP List
- I think the real robinhood uses the same page to show what you are describing under portfolio and user account. In my head they are the same feature as you are showing your balance, the stocks you own and your overall portfolio performance. Are you planning on having two separate pages to display this info? 
- [x] I encourage you to implement stock details before watchlist as that will make the site a lot more interesting. And if you decide to implement it later you may not get to it.

**Comment by MelodyLayne** [comment]
Hi Javier,

I actually had that though about the stock details when writing out the MVP's and then just didn't switch up the order. Thanks for the reminder.

As for the user account, my initial schema didn't include that, but I was trying to decide if I should have it as an added page so I wrote that schema as well. I can add the two pieces of the user account to the home page though and that would give it more to see without overcrowding it. I will have a revised schema for you in a few minutes.

**Comment by javiermortiz** [comment]
Is looking good, I would add a stockId and a count to the portfolio table just to make it easier to know the amount of stock you own. Otherwise you would need to query both the bought and sold tables, which doesn't sound fun at all.

**Comment by MelodyLayne** [comment]
That makes total sense and I have made that change as well.

**Comment by javiermortiz** [comment]
Cool, I think the association is flipped between portfolio and bought/sold stocks. 1 portfolio can have many bought/sold stocks, not the other way around. Minor change.
This is me giving you the hard approve on your schema.
